---
# handlers file for distcc
- name: systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: distccd restart
  ansible.builtin.service:
    name: distccd
    state: restarted
